#######################################################################################################################
services:
#######################################################################################################################
  db_app:
    build: 
      context: .
      dockerfile: files/docker/dockerfile_db
      args:
        - DB_ROOTPASSWORD=${DB_ROOTPASSWORD}
        - DB_APPUSER=${DB_APPUSER}
        - DB_APPPASS=${DB_APPPASS}
        - DB_NAME=${DB_NAME}
    container_name: TV_DUMP_DB
    hostname: gudangberkasdb
    volumes:
      - './config/db.backup.cnf:/root/.my.cnf'
      - './config/logrotate_backup.conf:/etc/logrotate_backup.conf'
      - './config/logrotate_cron:/etc/crontab'
    dns:
      - ${DNS1}
      - ${DNS2}
    networks:
      macvlan000:
        ipv4_address: ${DB_IPADDRESS}
#######################################################################################################################
  ws_app:
    build: 
      context: .
      dockerfile: files/docker/dockerfile_ws
    container_name: TV_DUMP_APP
    hostname: tvdump
    volumes:
      - './:/code/'
    dns:
      - ${DNS1}
      - ${DNS2}
    networks:
      macvlan000:
        ipv4_address: ${APP_IPADDRESS}
    depends_on:
      - db_app

#######################################################################################################################
  celery_worker:
    build: 
      context: .
      dockerfile: files/docker/dockerfile_celery
    container_name: TV_DUMP_WORKER
    command: celery -A app.main.celery worker --loglevel=info
    volumes:
      - './:/code/'
    dns:
      - ${DNS1}
      - ${DNS2}
    networks:
      macvlan000:
        ipv4_address: ${CELERY_IPADDRESS}
    depends_on:
      - ws_app
      - db_app

#######################################################################################################################
networks:
  macvlan000:
    external:
     name: ${MACVLAN}
